<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Maze.TApplication</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maze.Net\Maze.Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="control\CircularMazeControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

</Project>